parameters:
#    editor_imgeditor.example.class: Editor\ImgeditorBundle\Example

services:
#    editor_imgeditor.example:
#        class: %editor_imgeditor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
