Editor\ImgeditorBundle\Entity\Action:
    type: entity
    table: action
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: 'wiadomo - id'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idProject:
            type: string
            nullable: false
            length: 40
            fixed: true
            comment: 'id projektu - klucz w sesji generowany po udanym zapisaniu obrazka'
            column: id_project
        idAction:
            type: string
            nullable: false
            length: 40
            fixed: true
            comment: 'hash akcji (obroc, przytnij, itd) genrowany po wykonaniu kazdorazowej transformacji obrazka'
            column: id_action
        position:
            type: integer
            nullable: false
            unsigned: true
            comment: 'numer akcji - przydatny przy cofaniu  np.: 1, 2, 3, 4, 5'
        image:
            type: string
            nullable: false
            length: 50
            fixed: true
            comment: 'nazwa obrazka, nazwa jest np.: dwwfsewfmmcd.jpg'
        jsonData:
            type: string
            nullable: false
            length: 1000
            fixed: false
            comment: 'Dodatkowe dane w formacie json zwiazane z akcja np.: {"action" : "rotate"}'
            column: json_data
        created:
            type: datetime
            nullable: false
            comment: 'czas utworzenia akcji'
        updated:
            type: datetime
            nullable: false
            comment: 'czas aktualizacji akcji (np.: przy cofaniu)'
    lifecycleCallbacks: {  }
